# make use of vm's

language: ruby
# python:
#   - "3.5"

# have the docker service set up (we'll
# update it later)
services:
  - 'docker'

# prepare the machine before any code
# installation scripts
#before_install:
  #- './.travis/main.sh'

script: ./.travis/build.sh -b 